### ISSUE TITLE
Problems with new GCP example

### ISSUE THREAD

**Issue by verdurin** [ComputeCanada/magic_castle#63] opened 2020-02-27 00:31 UTC
With the new `main.tf` example for `GCP` I see these errors:
```

Error: Missing required argument

  on main.tf line 5, in module "gcp":
   5: module "gcp" {

The argument "gpu_per_node" is required, but no definition was found.


Error: Missing required argument

  on main.tf line 5, in module "gcp":
   5: module "gcp" {

The argument "project_name" is required, but no definition was found.


Error: Unsupported argument

  on main.tf line 35, in module "gcp":
  35:   project = "<project>"

An argument named "project" is not expected here.
```

**Comment by cmd-ntrf** [comment] 2020-02-27 17:39
There was an issue with travis deploy configuration. A newly introduced sed on module source in the "build" phase was had unexpected effect on the files released. This is now fixed in release 6.1.

If you use github example directly, make sure to call `terraform init -upgrade` if you put the new main.tf in a folder that used to contain a previous version of Magic Castle.

**Comment by verdurin** [comment] 2020-02-27 21:43
Thanks, have tried that, and removed the `.terraform` directory but I see this error:
```
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

module.gcp.data.http.hieradata_template: Refreshing state...
module.dns.data.google_dns_managed_zone.domain: Refreshing state...
module.gcp.data.google_compute_zones.available: Refreshing state...

Error: Call to unknown function

  on .terraform/modules/gcp/gcp/data.tf line 12, in locals:
  12:             for key in setsubtract(keys(node), ["prefix", "count"]):

There is no function named "setsubtract".


Error: googleapi: Error 404: The 'parameters.managedZone' resource named '<domain>' does not exist., notFound

  on .terraform/modules/dns/dns/gcloud/main.tf line 5, in data "google_dns_managed_zone" "domain":
   5: data "google_dns_managed_zone" "domain" {
```
This is with the latest `master`.

**Comment by verdurin** [comment] 2020-02-27 21:49
I see the second error with the `6.1` release too.

**Comment by cmd-ntrf** [comment] 2020-02-27 21:59
It was part of the release notes for 6.0, you need to upgrade Terraform to 0.12.21. It is not easy to highlight for previous users, but I tried ;).

**Comment by verdurin** [comment] 2020-02-27 22:03
Yes, the first error goes away with `0.12.21`. It's irritating that the GCP cloud shell retains a very old version in `/usr/local/bin`. I had upgraded it elsewhere...

**Comment by cmd-ntrf** [comment] 2020-02-27 22:31
I am unable to reproduce the error with the gcloud dns module.

The only way I was able to reproduce the error was with the following code:
```
provider "google" {
  version = "<3"
}
data "google_dns_managed_zone" "domain" {
  name    = "<domain>"
  project = "gcp-project-name"
}
```

Where the `name` variable is litterally set to `<domain>`. If you look at the `dns/gcloud/main.tf`, `name` is set from the `var.domain` which takes its value from the output of the previous module, in your case gcp. So you would have to define the domain in the Magic Castle gcp module to "<domain>". So it looks like a misconfiguration in your main.tf.

Could you share it?

**Comment by verdurin** [comment] 2020-02-27 22:37
Here you go, with again the actual domain censored:
```
terraform {
  required_version = ">= 0.12"
}

module "gcp" {
  source = "git::https://github.com/ComputeCanada/magic_castle.git//gcp"

  cluster_name = "tc16"
  domain       = "<my domain>"
  image        = "centos-7"
  nb_users     = 10

  instances = {
    mgmt  = { type = "n1-standard-2", count = 1 },
    login = { type = "n1-standard-2", count = 1 },
    node  = [
      { type = "n1-standard-2", count = 1 },
      # { type = "n1-standard-2", count = 1, prefix = "gpu", gpu_type = "nvidia-tesla-k80", gpu_count = 1 },
    ]
  }

  storage = {
    type         = "nfs"
    home_size    = 100
    project_size = 50
    scratch_size = 50
  }

  public_keys = [file("~/.ssh/id_rsa.pub")]

  # Shared password, randomly chosen if blank
  guest_passwd = ""

  # GCP specifics
  project = "<my GCP project>"
  region  = "eu-west2"
}

output "sudoer_username" {
  value = module.gcp.sudoer_username
}

output "guest_usernames" {
  value = module.gcp.guest_usernames
}

output "guest_passwd" {
  value = module.gcp.guest_passwd
}

output "public_ip" {
  value = module.gcp.ip
}

## Uncomment to register your domain name with CloudFlare
# module "dns" {
#   source           = "git::https://github.com/ComputeCanada/magic_castle.git//dns/cloudflare"
#   name             = module.gcp.cluster_name
#   domain           = module.gcp.domain
#   email            = "you@example.com"
#   public_ip        = module.gcp.ip
#   rsa_public_key   = module.gcp.rsa_public_key
#   sudoer_username  = module.gcp.sudoer_username
# }

module "dns" {
  source           = "git::https://github.com/ComputeCanada/magic_castle.git//dns/gcloud"
  email            = "<my e-mail>"
  project          = "<my project>"
  zone_name        = "<my Cloud DNS zone> "
  name             = module.gcp.cluster_name
  domain           = module.gcp.domain
  public_ip        = module.gcp.ip
  rsa_public_key   = module.gcp.rsa_public_key
  sudoer_username  = module.gcp.sudoer_username
}

output "hostnames" {
        value = module.dns.hostnames
}

**Comment by verdurin** [comment] 2020-02-27 22:39
Yes, you were right as usual.
I put the actual zone, rather than the zone name in the `zone_name` field. Bah.

Working now.

**Closed** 2020-02-27 22:41 UTC
